import type { Metadata } from "next";
import LenisProvider from "@/components/utils/providers/lenis-provider";
import Header from "@/components/layouts/header";
import { getUserByUsername } from "@/actions/user/get";
import { MAIN_USERNAME } from "@/lib/db";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserByUsername(MAIN_USERNAME);

  return (
    <>
      <Header user={user} />
      <LenisProvider>
        <main>{children}</main>
      </LenisProvider>
    </>
  );
}
