import type { Metadata } from "next";
import LenisProvider from "@/components/utils/providers/lenis-provider";
import Header from "@/components/layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <LenisProvider>
        <main>{children}</main>
      </LenisProvider>
    </>
  );
}
